### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by ytabira** [kddnewton/humidifier#312]
Hello, thanks for this useful software.
I have been trying `humidifier upgrade`. And I get an error:
Is there a workaround?

```
$ ./humidifier upgrade
Traceback (most recent call last):
        8739: from ./humidifier:8:in `<main>'
        8738: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/inline.rb:54:in `gemfile'
        8737: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/settings.rb:124:in `temporary'
        8736: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/inline.rb:70:in `block in gemfile'
        8735: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        8734: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        8733: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
        8732: from /Users/ytabira/.anyenv/envs/rbenv/versions/2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
         ... 8727 levels...
           4: from /Users/ytabira/.anyenv/envs/rbenv/gems/2.7.0/gems/humidifier-4.1.1/lib/humidifier/props.rb:169:in `block in subprops_from'
           3: from /Users/ytabira/.anyenv/envs/rbenv/gems/2.7.0/gems/humidifier-4.1.1/lib/humidifier/props.rb:187:in `from'
           2: from /Users/ytabira/.anyenv/envs/rbenv/gems/2.7.0/gems/humidifier-4.1.1/lib/humidifier/props.rb:201:in `singular_from'
           1: from /Users/ytabira/.anyenv/envs/rbenv/gems/2.7.0/gems/humidifier-4.1.1/lib/humidifier/props.rb:201:in `new'
/Users/ytabira/.anyenv/envs/rbenv/gems/2.7.0/gems/humidifier-4.1.1/lib/humidifier/props.rb:138:in `initialize': stack level too deep (SystemStackError)
```

Thanks in advance.

**Comment by kddnewton** [comment]
Fixed in #329, it'll be out in the next release momentarily.
